name: Publish package to the Maven Central Repository and GitHub Packages
on:
  release:
    types: [published]
jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish artifact
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #   # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
      #   # If we split on '/' and take the 3rd value,
      #   # we can get the release name.
      #   run: |
      #     NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
      #     echo "New version: ${NEW_VERSION}"
      #     echo "Github username: ${GITHUB_ACTOR}"
      #     ./gradlew -Pversion=${NEW_VERSION} publish